### PR TITLE
Update AMI for region eu-central-1

### PR DESCRIPTION
**Pull request by juanmacintas**
I have updated the ami for frankfurt (eu-central-1)

### CODE REVIEW

**Comment by dsingh07** [comment]
Hi @juanmacintas thanks for the PR! Do you mind updating the AMI ID for all the regions please?

**Comment by juanmacintas** [comment]
Sure! I have updated all values!

**Comment by dsingh07** [comment]
@juanmacintas Thanks for the updates! Can you squash your commits please?

**Comment by ranaskr** [comment]
I had the similar issue when I was provisioning ADOP C in London Region (eu-west-2). Referring to the right AMI from this portal https://wiki.centos.org/Cloud/AWS and modifying the CF Templates to use the correct AMI worked!!

Please make an update to pick the right ami as this was creating confusion before I found the solution.

**Review by restalion — CHANGES_REQUESTED** [review]
Some discrepancies in AMIs:

- ap-south-1 should be ami-3d9ec952
- ap-southeast-1 should be ami-74fb8908 
- ap-southeast-2 should be ami-b0ba46d2

Could you update wrong AMIs?

Best regards,

**Review by restalion — APPROVED** [review]
Now AMIs are alligned with the ones in this URL: https://wiki.centos.org/Cloud/AWS

**Review by restalion — APPROVED** [review]
AMIs are now updated.

**Comment by dsingh07** [comment]
Closing this PR due to inactivity and new AMIs are covered here: https://github.com/Accenture/adop-aws/pull/14

**Pull request closed without merging**
